### PR TITLE
CI: GitHub Actions

### PR DESCRIPTION
**Pull request by kmoe**
Remove the old Travis config, and run PR tests via GitHub Actions.

The `krb5-user` package is required for `kinit`, used in `acceptance.sh`.

We skip `TestAccDataDnsTxtRecordSet_Basic` due to a failure we can't reproduce anywhere except the GHA runner and will need to investigate later: https://github.com/hashicorp/terraform-provider-dns/issues/154

### CODE REVIEW

**Comment by bflad** [comment]
Ready for updates from other similar pull requests! 👍

**Comment by kmoe** [comment]
Could the fail be related to the CGO DNS issues (https://github.com/golang/go/issues/25321 etc)?

**Comment by kmoe** [comment]
The test failure:
```
=== RUN   TestAccDataDnsTxtRecordSet_Basic
    data_dns_txt_record_set_test.go:13: Step 1/1 error: Error running pre-apply refresh: exit status 1
        2021/06/24 15:53:58 [DEBUG] Using modified User-Agent: Terraform/0.12.30 HashiCorp-terraform-exec/0.13.3
        
        Error: error looking up TXT records for "terraform.io": lookup terraform.io on 127.0.0.53:53: no such host
        
          on terraform_plugin_test.tf line 2, in data "dns_txt_record_set" "test":
           2: data "dns_txt_record_set" "test" {
        
        
--- FAIL: TestAccDataDnsTxtRecordSet_Basic (11.55s)
```

**Comment by bflad** [comment]
macOS support may require some parts of https://github.com/hashicorp/terraform-provider-dns/pull/144, but unsure how the runners differ from an actual workstation.

**Review by bflad — APPROVED** [review]
Looks great! Thank you for opening that separate issue and implementing the TXT data source test workaround for now. 🚀

**Pull request merged**
