### PR TITLE
Add support for importing resources

### LINKED ISSUE #3: dns_a_record_set works incorrectly
_This issue was originally opened by @andrey-iliyov as hashicorp/terraform#15537. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
dns_a_record_set

### Terraform Configuration Files
```hcl
resource "dns_a_record_set" "www" {
  zone = "example.com."
  name = "www"
  addresses = [
    "192.168.0.200",
  ]
  ttl = 300
}
```

### Expected Behavior
Before I execute `terraform apply` I had DNS record created manually:
```hcl
cli> host www.example.com
www.example.com has address 10.10.10.10
```
After I launched `terraform apply` I have terraform error and DNS records:
```hcl
cli> host www.example.com
www.example.com has address 10.10.10.10
www.example.com has address 192.168.0.200
```
So I expect that DNS record should be replaced(old value of DNS record should be deleted) by default. 

Or can you add `dns_a_record_set` Argument `recreate_record` ? When `recreate_record=true` then if old value of DNS record exist it should be replaced with new value. 

Thanks!

### Actual Behavior
Error applying plan:
```hcl
2 error(s) occurred:

* dns_a_record_set.www[1]: 1 error(s) occurred:

* dns_a_record_set.www.1: DNS record differs
* dns_a_record_set.www[0]: 1 error(s) occurred:

* dns_a_record_set.www.0: DNS record differs

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### PR DESCRIPTION
**Pull request by bodgit**
This builds on top of #35 and #36 and re-fixes #13 in a slightly different way in order to add support for importing resources. This also should fix #3 in a manner of speaking.

### CODE REVIEW

**Comment by bodgit** [comment]
This seems to still show the commits from #36, I'll see if I can tidy this up so it's easier to review.

**Comment by bodgit** [comment]
@katbyte The diff should look much better now. Tests all pass:
```
$ ./dns/acceptance.sh
+ export DNS_DOMAIN_FORWARD=example.com.
+ DNS_DOMAIN_FORWARD=example.com.
+ export DNS_DOMAIN_REVERSE=1.168.192.in-addr.arpa.
+ DNS_DOMAIN_REVERSE=1.168.192.in-addr.arpa.
+ DOCKER_CONTAINER_NAME=tf_acc_dns
+ export DNS_UPDATE_SERVER=127.0.0.1
+ DNS_UPDATE_SERVER=127.0.0.1
+ export DNS_UPDATE_PORT=55354
+ DNS_UPDATE_PORT=55354
+ docker run -d -p 55354:53/udp -e BIND_DOMAIN_FORWARD=example.com. -e BIND_DOMAIN_REVERSE=1.168.192.in-addr.arpa. -e BIND_INSECURE=true --name tf_acc_dns drebes/bind
d8a99a640818b67df224628dfe7edf7958703ac28ac643415b4423b4ccbc9552
+ make testacc TEST=./dns
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./dns -v  -timeout 120m
=== RUN   TestAccDataDnsARecordSet_Basic
--- PASS: TestAccDataDnsARecordSet_Basic (0.52s)
=== RUN   TestAccDataDnsAAAARecordSet_Basic
--- PASS: TestAccDataDnsAAAARecordSet_Basic (0.03s)
=== RUN   TestAccDataDnsCnameRecordSet_Basic
--- PASS: TestAccDataDnsCnameRecordSet_Basic (0.11s)
=== RUN   TestAccDataDnsNSRecordSet_Basic
--- PASS: TestAccDataDnsNSRecordSet_Basic (0.04s)
=== RUN   TestAccDataDnsPtrRecordSet_Basic
--- PASS: TestAccDataDnsPtrRecordSet_Basic (0.03s)
=== RUN   TestAccDataDnsTxtRecordSet_Basic
--- PASS: TestAccDataDnsTxtRecordSet_Basic (0.06s)
=== RUN   TestHashIPString
--- PASS: TestHashIPString (0.00s)
=== RUN   TestAccDnsARecordSet_importBasic
--- PASS: TestAccDnsARecordSet_importBasic (0.18s)
=== RUN   TestAccDnsAAAARecordSet_importBasic
--- PASS: TestAccDnsAAAARecordSet_importBasic (0.03s)
=== RUN   TestAccDnsCnameRecord_importBasic
--- PASS: TestAccDnsCnameRecord_importBasic (0.03s)
=== RUN   TestAccDnsNSRecordSet_importBasic
--- PASS: TestAccDnsNSRecordSet_importBasic (0.03s)
=== RUN   TestAccDnsPtrRecord_importBasic
--- PASS: TestAccDnsPtrRecord_importBasic (0.03s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccDnsARecordSet_Basic
--- PASS: TestAccDnsARecordSet_Basic (0.07s)
=== RUN   TestAccDnsAAAARecordSet_basic
--- PASS: TestAccDnsAAAARecordSet_basic (0.09s)
=== RUN   TestAccDnsCnameRecord_basic
--- PASS: TestAccDnsCnameRecord_basic (0.07s)
=== RUN   TestAccDnsNSRecordSet_Basic
--- PASS: TestAccDnsNSRecordSet_Basic (0.07s)
=== RUN   TestAccDnsPtrRecord_basic
--- PASS: TestAccDnsPtrRecord_basic (0.07s)
=== RUN   TestValidateZone
--- PASS: TestValidateZone (0.00s)
=== RUN   TestValidateName
--- PASS: TestValidateName (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-dns/dns       1.478s
+ cleanup_docker
+ docker stop tf_acc_dns
tf_acc_dns
+ docker rm tf_acc_dns
tf_acc_dns
+ export DNS_UPDATE_KEYNAME=example.com.
+ DNS_UPDATE_KEYNAME=example.com.
+ export DNS_UPDATE_KEYALGORITHM=hmac-md5
+ DNS_UPDATE_KEYALGORITHM=hmac-md5
+ export DNS_UPDATE_KEYSECRET=c3VwZXJzZWNyZXQ=
+ DNS_UPDATE_KEYSECRET=c3VwZXJzZWNyZXQ=
+ docker run -d -p 55354:53/udp -e BIND_DOMAIN_FORWARD=example.com. -e BIND_DOMAIN_REVERSE=1.168.192.in-addr.arpa. -e BIND_KEY_NAME=example.com. -e BIND_KEY_ALGORITHM=hmac-md5 -e BIND_KEY_SECRET=c3VwZXJzZWNyZXQ= --name tf_acc_dns drebes/
bind
9b90fcb85334ea091fcbca53b98f29756033bea2f72cbe5b166778868125237f
+ make testacc TEST=./dns
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./dns -v  -timeout 120m
=== RUN   TestAccDataDnsARecordSet_Basic
--- PASS: TestAccDataDnsARecordSet_Basic (0.07s)
=== RUN   TestAccDataDnsAAAARecordSet_Basic
--- PASS: TestAccDataDnsAAAARecordSet_Basic (0.03s)
=== RUN   TestAccDataDnsCnameRecordSet_Basic
--- PASS: TestAccDataDnsCnameRecordSet_Basic (0.03s)
=== RUN   TestAccDataDnsNSRecordSet_Basic
--- PASS: TestAccDataDnsNSRecordSet_Basic (0.03s)
=== RUN   TestAccDataDnsPtrRecordSet_Basic
--- PASS: TestAccDataDnsPtrRecordSet_Basic (0.03s)
=== RUN   TestAccDataDnsTxtRecordSet_Basic
--- PASS: TestAccDataDnsTxtRecordSet_Basic (0.04s)
=== RUN   TestHashIPString
--- PASS: TestHashIPString (0.00s)
=== RUN   TestAccDnsARecordSet_importBasic
--- PASS: TestAccDnsARecordSet_importBasic (0.03s)
=== RUN   TestAccDnsAAAARecordSet_importBasic
--- PASS: TestAccDnsAAAARecordSet_importBasic (0.03s)
=== RUN   TestAccDnsCnameRecord_importBasic
--- PASS: TestAccDnsCnameRecord_importBasic (0.03s)
=== RUN   TestAccDnsNSRecordSet_importBasic
--- PASS: TestAccDnsNSRecordSet_importBasic (0.03s)
=== RUN   TestAccDnsPtrRecord_importBasic
--- PASS: TestAccDnsPtrRecord_importBasic (0.03s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccDnsARecordSet_Basic
--- PASS: TestAccDnsARecordSet_Basic (0.57s)
=== RUN   TestAccDnsAAAARecordSet_basic
--- PASS: TestAccDnsAAAARecordSet_basic (0.10s)
=== RUN   TestAccDnsCnameRecord_basic
--- PASS: TestAccDnsCnameRecord_basic (0.07s)
=== RUN   TestAccDnsNSRecordSet_Basic
--- PASS: TestAccDnsNSRecordSet_Basic (0.07s)
=== RUN   TestAccDnsPtrRecord_basic
--- PASS: TestAccDnsPtrRecord_basic (0.07s)
=== RUN   TestValidateZone
--- PASS: TestValidateZone (0.00s)
=== RUN   TestValidateName
--- PASS: TestValidateName (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-dns/dns       1.269s
+ cleanup_docker
+ docker stop tf_acc_dns
tf_acc_dns
+ docker rm tf_acc_dns
tf_acc_dns
```
I kept the import tests separate as that's how they're arranged in the AWS provider which I used as as example.

**Comment by katbyte** [comment]
@bodgit,

The AWS provider is moving towards having the tests at the end of the regular tests [as can be seen here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codebuild_webhook_test.go#L37-L41).

**Comment by bodgit** [comment]
Ok, in that case I'll look to merge the import tests.

**Comment by bodgit** [comment]
@katbyte Import tests merged, everything still passes. Ok?

**Pull request merged**
